export type EvidenceScore = "A" | "B" | "C" | "D"

export type CommercialRestriction =
  | "open" // affiliate promotion allowed where legally permitted
  | "restricted" // no direct affiliate promotion allowed

export interface Peptide {
  slug: string
  name: string
  aliases: string[]
  category: string
  evidenceScore: EvidenceScore
  riskFlag: boolean
  commercialRestriction: CommercialRestriction
  regulatoryStatus: string
  summary: string
  whatIsIt: string
  mechanisms: string[]
  humanEvidence: string
  animalEvidence: string
  safetySummary: string
  knownSideEffects: string[]
  commonDiscussion: string[]
  lastReviewed: string
  reviewedBy: string
}

export const EVIDENCE_SCORE_META: Record<
  EvidenceScore,
  { label: string; description: string; tone: "high" | "mid" | "low" }
> = {
  A: {
    label: "A — Approved / Strong",
    description: "Approved medical use or strong clinical evidence.",
    tone: "high",
  },
  B: {
    label: "B — Human, limited",
    description: "Human evidence exists but is limited.",
    tone: "mid",
  },
  C: {
    label: "C — Early / Preclinical",
    description: "Mostly early human, animal, or mechanistic data.",
    tone: "mid",
  },
  D: {
    label: "D — Anecdotal",
    description: "Anecdotal or insufficient evidence.",
    tone: "low",
  },
}

export const peptides: Peptide[] = [
  {
    slug: "bpc-157",
    name: "BPC-157",
    aliases: ["Body Protection Compound-157", "PL 14736"],
    category: "Recovery / Regeneration",
    evidenceScore: "C",
    riskFlag: true,
    commercialRestriction: "restricted",
    regulatoryStatus:
      "Not an approved medicine in the EU/US. Sold as a research chemical only; not authorised for human use.",
    summary:
      "A synthetic peptide fragment widely discussed for soft-tissue recovery. Human clinical evidence is very limited; most data is animal or mechanistic.",
    whatIsIt:
      "BPC-157 is a synthetic 15-amino-acid sequence derived from a protein found in gastric juice. It is discussed in the community mainly in the context of tendon, ligament, and gut-related recovery.",
    mechanisms: [
      "Proposed promotion of angiogenesis (new blood-vessel formation)",
      "Discussed modulation of growth-factor and nitric-oxide pathways",
      "Proposed effects on fibroblast activity in connective tissue",
    ],
    humanEvidence:
      "Peer-reviewed human clinical trials are essentially absent. Claims about human recovery are extrapolated from animal work and personal reports.",
    animalEvidence:
      "A body of rodent studies reports accelerated healing of tendon, muscle, and gut tissue. These results have not been replicated in controlled human trials.",
    safetySummary:
      "Human safety data is lacking. Purity, sterility, and dosing of research-grade material are unverified. This is not a substitute for professional medical care.",
    knownSideEffects: [
      "Injection-site reactions reported anecdotally",
      "Unknown long-term safety profile",
    ],
    commonDiscussion: ["Tendon and ligament recovery", "Gut discomfort", "Post-injury reports"],
    lastReviewed: "2026-06-01",
    reviewedBy: "Editorial team (AI-assisted draft, human-reviewed)",
  },
  {
    slug: "tb-500",
    name: "TB-500 / Thymosin Beta-4",
    aliases: ["Thymosin Beta-4", "TB4"],
    category: "Recovery / Regeneration",
    evidenceScore: "C",
    riskFlag: true,
    commercialRestriction: "restricted",
    regulatoryStatus:
      "Not an approved medicine for general human use. Research chemical status in most jurisdictions.",
    summary:
      "A peptide related to the naturally occurring protein Thymosin Beta-4, discussed for recovery and regeneration. Human evidence is limited.",
    whatIsIt:
      "TB-500 is a synthetic fragment associated with Thymosin Beta-4, a protein involved in cell migration and actin regulation.",
    mechanisms: [
      "Proposed regulation of actin, supporting cell migration",
      "Discussed roles in angiogenesis and tissue repair",
    ],
    humanEvidence:
      "Limited. Thymosin Beta-4 itself has been studied in some clinical contexts, but the research-market 'TB-500' fragment lacks robust human trials.",
    animalEvidence: "Animal studies suggest roles in wound healing and cardiac tissue repair.",
    safetySummary:
      "Human safety data is limited. Material sold on the research market is not quality-assured for human use.",
    knownSideEffects: ["Fatigue reported anecdotally", "Unknown long-term profile"],
    commonDiscussion: ["Recovery reports", "Comparison with BPC-157"],
    lastReviewed: "2026-06-01",
    reviewedBy: "Editorial team (AI-assisted draft, human-reviewed)",
  },
  {
    slug: "ghk-cu",
    name: "GHK-Cu",
    aliases: ["Copper Peptide", "Copper tripeptide-1"],
    category: "Skin / Cosmetic",
    evidenceScore: "B",
    riskFlag: false,
    commercialRestriction: "open",
    regulatoryStatus:
      "Widely used as a cosmetic ingredient in topical products. Cosmetic use is broadly permitted; injectable use is a separate matter.",
    summary:
      "A copper-binding tripeptide common in cosmetics. There is reasonable evidence for topical skin benefits; systemic/injected use is far less studied.",
    whatIsIt:
      "GHK-Cu is a naturally occurring copper-binding peptide used extensively in topical skincare formulations.",
    mechanisms: [
      "Copper delivery relevant to skin remodelling",
      "Discussed effects on collagen and antioxidant pathways",
    ],
    humanEvidence:
      "Topical cosmetic studies report improvements in skin appearance. Evidence for injected/systemic use is limited.",
    animalEvidence: "Animal and in-vitro work supports wound-healing and skin-remodelling roles.",
    safetySummary:
      "Topical cosmetic use is generally well tolerated. Injected use is not a validated cosmetic route and carries different risks.",
    knownSideEffects: ["Topical irritation in some users"],
    commonDiscussion: ["Skin quality", "Hair", "Topical vs injected"],
    lastReviewed: "2026-06-01",
    reviewedBy: "Editorial team (AI-assisted draft, human-reviewed)",
  },
  {
    slug: "kpv",
    name: "KPV",
    aliases: ["Lysine-Proline-Valine"],
    category: "Inflammation",
    evidenceScore: "C",
    riskFlag: false,
    commercialRestriction: "restricted",
    regulatoryStatus: "Not an approved medicine. Research chemical status.",
    summary:
      "A short tripeptide fragment of alpha-MSH discussed in the context of inflammation. Human evidence is limited.",
    whatIsIt: "KPV is the C-terminal tripeptide of the alpha-MSH hormone, studied for anti-inflammatory properties.",
    mechanisms: ["Discussed anti-inflammatory signalling", "Proposed effects on gut inflammation"],
    humanEvidence: "Very limited human data.",
    animalEvidence: "Preclinical work suggests anti-inflammatory activity in models of colitis.",
    safetySummary: "Human safety data is limited; research-market purity is unverified.",
    knownSideEffects: ["Unknown long-term profile"],
    commonDiscussion: ["Gut inflammation", "Skin"],
    lastReviewed: "2026-06-01",
    reviewedBy: "Editorial team (AI-assisted draft, human-reviewed)",
  },
  {
    slug: "semax",
    name: "Semax",
    aliases: ["ACTH(4-7) analogue"],
    category: "Cognitive",
    evidenceScore: "C",
    riskFlag: false,
    commercialRestriction: "restricted",
    regulatoryStatus:
      "Approved/used as a medicine in some countries (e.g. Russia); not approved in the EU/US.",
    summary:
      "A peptide discussed for cognitive and neuroprotective effects. Approved in some jurisdictions but not others.",
    whatIsIt: "Semax is a synthetic peptide derived from an ACTH fragment, studied for nootropic and neuroprotective effects.",
    mechanisms: ["Discussed modulation of BDNF", "Proposed neuroprotective signalling"],
    humanEvidence: "Some human studies exist in the countries where it is used clinically; broader independent replication is limited.",
    animalEvidence: "Preclinical work reports neuroprotective and cognitive effects.",
    safetySummary: "Where used clinically it is intranasal and prescribed; research-market use is unverified.",
    knownSideEffects: ["Nasal irritation with intranasal use reported"],
    commonDiscussion: ["Focus", "Mood", "Comparison with Selank"],
    lastReviewed: "2026-06-01",
    reviewedBy: "Editorial team (AI-assisted draft, human-reviewed)",
  },
  {
    slug: "selank",
    name: "Selank",
    aliases: ["TP-7 analogue"],
    category: "Cognitive / Mood",
    evidenceScore: "C",
    riskFlag: false,
    commercialRestriction: "restricted",
    regulatoryStatus: "Used as a medicine in some countries; not approved in the EU/US.",
    summary: "An anxiolytic-discussed peptide analogue. Approved in some jurisdictions, limited independent evidence elsewhere.",
    whatIsIt: "Selank is a synthetic analogue of the endogenous peptide tuftsin, studied for anxiolytic effects.",
    mechanisms: ["Discussed effects on GABA and monoamine systems"],
    humanEvidence: "Some regional clinical use; limited independent replication.",
    animalEvidence: "Preclinical anxiolytic effects reported.",
    safetySummary: "Research-market purity is unverified; not a validated treatment outside its regional approvals.",
    knownSideEffects: ["Nasal irritation with intranasal use reported"],
    commonDiscussion: ["Anxiety", "Sleep", "Stacking with Semax"],
    lastReviewed: "2026-06-01",
    reviewedBy: "Editorial team (AI-assisted draft, human-reviewed)",
  },
  {
    slug: "epitalon",
    name: "Epitalon",
    aliases: ["Epithalon", "AEDG"],
    category: "Longevity",
    evidenceScore: "D",
    riskFlag: false,
    commercialRestriction: "restricted",
    regulatoryStatus: "Not an approved medicine. Research chemical status.",
    summary: "A tetrapeptide discussed in longevity circles for telomerase-related claims. Human evidence is weak.",
    whatIsIt: "Epitalon is a synthetic tetrapeptide studied primarily in Russian gerontology research.",
    mechanisms: ["Proposed effects on telomerase activity", "Discussed circadian and pineal effects"],
    humanEvidence: "Sparse and largely from a small number of research groups; independent replication is limited.",
    animalEvidence: "Some rodent longevity data reported by originating groups.",
    safetySummary: "Human safety data is weak. Claims should be treated with caution.",
    knownSideEffects: ["Unknown long-term profile"],
    commonDiscussion: ["Longevity", "Sleep", "Telomeres"],
    lastReviewed: "2026-06-01",
    reviewedBy: "Editorial team (AI-assisted draft, human-reviewed)",
  },
  {
    slug: "mots-c",
    name: "MOTS-c",
    aliases: ["Mitochondrial ORF of the 12S rRNA type-c"],
    category: "Metabolic",
    evidenceScore: "C",
    riskFlag: false,
    commercialRestriction: "restricted",
    regulatoryStatus: "Not an approved medicine. Research chemical status.",
    summary: "A mitochondrial-derived peptide discussed for metabolic effects. Mostly preclinical evidence.",
    whatIsIt: "MOTS-c is a peptide encoded in mitochondrial DNA, studied for roles in metabolism and exercise physiology.",
    mechanisms: ["Discussed AMPK activation", "Proposed metabolic-regulation roles"],
    humanEvidence: "Limited; mostly observational and mechanistic.",
    animalEvidence: "Rodent studies report effects on insulin sensitivity and metabolism.",
    safetySummary: "Human safety data is limited; research-market material is unverified.",
    knownSideEffects: ["Unknown long-term profile"],
    commonDiscussion: ["Metabolism", "Endurance"],
    lastReviewed: "2026-06-01",
    reviewedBy: "Editorial team (AI-assisted draft, human-reviewed)",
  },
  {
    slug: "dsip",
    name: "DSIP",
    aliases: ["Delta Sleep-Inducing Peptide"],
    category: "Sleep",
    evidenceScore: "D",
    riskFlag: false,
    commercialRestriction: "restricted",
    regulatoryStatus: "Not an approved medicine. Research chemical status.",
    summary: "A peptide historically studied for sleep. Human evidence is old and inconsistent.",
    whatIsIt: "DSIP is a neuropeptide first described in relation to sleep regulation.",
    mechanisms: ["Discussed effects on sleep architecture and stress hormones"],
    humanEvidence: "Older human studies exist with mixed and inconsistent results.",
    animalEvidence: "Mixed preclinical findings.",
    safetySummary: "Human safety data is limited and dated.",
    knownSideEffects: ["Unknown long-term profile"],
    commonDiscussion: ["Sleep quality", "Stress"],
    lastReviewed: "2026-06-01",
    reviewedBy: "Editorial team (AI-assisted draft, human-reviewed)",
  },
  {
    slug: "ipamorelin",
    name: "Ipamorelin",
    aliases: ["Growth hormone secretagogue"],
    category: "Growth Hormone Secretagogue",
    evidenceScore: "C",
    riskFlag: true,
    commercialRestriction: "restricted",
    regulatoryStatus: "Not an approved medicine for general use. Research chemical status.",
    summary: "A growth-hormone secretagogue discussed for recovery and body composition. Limited human trial evidence.",
    whatIsIt: "Ipamorelin is a selective growth-hormone secretagogue peptide.",
    mechanisms: ["Stimulation of growth-hormone release via ghrelin-receptor pathways"],
    humanEvidence: "Some early clinical study history; not an approved therapy.",
    animalEvidence: "Preclinical GH-release effects documented.",
    safetySummary: "Hormonal effects carry real risks; not a validated therapy. Professional supervision matters for anything hormonal.",
    knownSideEffects: ["Water retention reported", "Headache reported"],
    commonDiscussion: ["Recovery", "Sleep", "Stacking with CJC-1295"],
    lastReviewed: "2026-06-01",
    reviewedBy: "Editorial team (AI-assisted draft, human-reviewed)",
  },
  {
    slug: "cjc-1295",
    name: "CJC-1295",
    aliases: ["GRF analogue"],
    category: "Growth Hormone Secretagogue",
    evidenceScore: "C",
    riskFlag: true,
    commercialRestriction: "restricted",
    regulatoryStatus: "Not an approved medicine for general use. Research chemical status.",
    summary: "A growth-hormone-releasing factor analogue, often discussed alongside Ipamorelin. Limited human evidence.",
    whatIsIt: "CJC-1295 is a synthetic analogue of growth-hormone-releasing hormone (GHRH).",
    mechanisms: ["Stimulation of endogenous growth-hormone release"],
    humanEvidence: "Limited early clinical history; not an approved therapy.",
    animalEvidence: "Preclinical GH-axis effects documented.",
    safetySummary: "Hormonal effects carry real risks; not a validated therapy.",
    knownSideEffects: ["Injection-site reactions reported", "Water retention reported"],
    commonDiscussion: ["GH axis", "Recovery"],
    lastReviewed: "2026-06-01",
    reviewedBy: "Editorial team (AI-assisted draft, human-reviewed)",
  },
  {
    slug: "aod-9604",
    name: "AOD-9604",
    aliases: ["hGH fragment 176-191"],
    category: "Metabolic",
    evidenceScore: "C",
    riskFlag: false,
    commercialRestriction: "restricted",
    regulatoryStatus: "Not an approved weight-loss medicine; clinical development did not lead to approval.",
    summary: "A growth-hormone fragment once investigated for fat loss. Clinical trials did not lead to approval.",
    whatIsIt: "AOD-9604 is a fragment of human growth hormone investigated for metabolic effects.",
    mechanisms: ["Discussed effects on lipolysis without the full GH profile"],
    humanEvidence: "Clinical trials for obesity did not demonstrate sufficient efficacy for approval.",
    animalEvidence: "Some preclinical lipolytic effects reported.",
    safetySummary: "Not an approved therapy; efficacy for fat loss is not established.",
    knownSideEffects: ["Unknown long-term profile"],
    commonDiscussion: ["Fat loss", "Metabolism"],
    lastReviewed: "2026-06-01",
    reviewedBy: "Editorial team (AI-assisted draft, human-reviewed)",
  },
  {
    slug: "melanotan-1",
    name: "Melanotan I",
    aliases: ["Afamelanotide (related)"],
    category: "Pigmentation",
    evidenceScore: "B",
    riskFlag: true,
    commercialRestriction: "restricted",
    regulatoryStatus:
      "A related compound (afamelanotide) is an approved medicine for a rare condition; research-market Melanotan I is not.",
    summary: "A melanocortin agonist related to an approved medicine. Research-market use is unregulated and carries risks.",
    whatIsIt: "Melanotan I is a synthetic analogue of alpha-MSH affecting pigmentation.",
    mechanisms: ["Melanocortin-1 receptor agonism affecting melanin production"],
    humanEvidence: "The related approved drug has clinical evidence for a specific rare condition; general research-market use does not.",
    animalEvidence: "Melanocortin effects well characterised preclinically.",
    safetySummary: "Unregulated research-market use carries risks including effects on existing moles; dermatological monitoring matters.",
    knownSideEffects: ["Nausea reported", "Darkening of moles/freckles reported"],
    commonDiscussion: ["Pigmentation", "Photoprotection context"],
    lastReviewed: "2026-06-01",
    reviewedBy: "Editorial team (AI-assisted draft, human-reviewed)",
  },
  {
    slug: "melanotan-2",
    name: "Melanotan II",
    aliases: ["MT-2"],
    category: "Pigmentation",
    evidenceScore: "C",
    riskFlag: true,
    commercialRestriction: "restricted",
    regulatoryStatus: "Not an approved medicine. Sale for human use is restricted in many countries.",
    summary: "A non-selective melanocortin agonist widely flagged by regulators for safety concerns.",
    whatIsIt: "Melanotan II is a synthetic melanocortin agonist affecting pigmentation and other pathways.",
    mechanisms: ["Non-selective melanocortin-receptor agonism"],
    humanEvidence: "No approval; multiple regulator safety warnings exist.",
    animalEvidence: "Melanocortin effects characterised preclinically.",
    safetySummary: "Regulators have issued safety warnings. Effects on moles, blood pressure, and other systems are of concern.",
    knownSideEffects: ["Nausea", "Flushing", "Darkening of moles reported"],
    commonDiscussion: ["Pigmentation", "Safety warnings"],
    lastReviewed: "2026-06-01",
    reviewedBy: "Editorial team (AI-assisted draft, human-reviewed)",
  },
  {
    slug: "thymosin-alpha-1",
    name: "Thymosin Alpha-1",
    aliases: ["Ta1", "Thymalfasin"],
    category: "Immune",
    evidenceScore: "B",
    riskFlag: false,
    commercialRestriction: "restricted",
    regulatoryStatus:
      "Approved as a medicine (thymalfasin) in some countries for specific indications; not universally approved.",
    summary: "An immune-modulating peptide approved in some countries for specific conditions.",
    whatIsIt: "Thymosin Alpha-1 is a peptide involved in immune regulation, marketed as thymalfasin in some regions.",
    mechanisms: ["Immune modulation, including effects on T-cell function"],
    humanEvidence: "Clinical evidence exists for specific approved indications in the countries where it is registered.",
    animalEvidence: "Immune-modulating effects documented preclinically.",
    safetySummary: "Where approved it is prescribed and monitored; research-market use is unverified.",
    knownSideEffects: ["Injection-site reactions reported"],
    commonDiscussion: ["Immune support context", "Approved use vs research use"],
    lastReviewed: "2026-06-01",
    reviewedBy: "Editorial team (AI-assisted draft, human-reviewed)",
  },
  {
    slug: "ll-37",
    name: "LL-37",
    aliases: ["Cathelicidin fragment"],
    category: "Antimicrobial / Immune",
    evidenceScore: "C",
    riskFlag: false,
    commercialRestriction: "restricted",
    regulatoryStatus: "Not an approved medicine. Research chemical status.",
    summary: "An antimicrobial peptide studied for immune and antimicrobial roles. Mostly preclinical.",
    whatIsIt: "LL-37 is a human cathelicidin-derived antimicrobial peptide.",
    mechanisms: ["Antimicrobial activity", "Immune-modulating roles"],
    humanEvidence: "Limited; largely mechanistic and preclinical.",
    animalEvidence: "Antimicrobial and immune effects reported.",
    safetySummary: "Human safety data is limited; research-market material is unverified.",
    knownSideEffects: ["Unknown long-term profile"],
    commonDiscussion: ["Immune", "Skin"],
    lastReviewed: "2026-06-01",
    reviewedBy: "Editorial team (AI-assisted draft, human-reviewed)",
  },
  {
    slug: "kisspeptin-10",
    name: "Kisspeptin-10",
    aliases: ["KP-10"],
    category: "Endocrine",
    evidenceScore: "B",
    riskFlag: true,
    commercialRestriction: "restricted",
    regulatoryStatus: "Investigational; used in some clinical research settings. Not a general-use medicine.",
    summary: "A reproductive-hormone-axis peptide studied in clinical research. Not a consumer product.",
    whatIsIt: "Kisspeptin-10 is a peptide central to the regulation of reproductive hormones.",
    mechanisms: ["Stimulation of GnRH and downstream reproductive hormones"],
    humanEvidence: "Studied in controlled clinical research on reproductive endocrinology.",
    animalEvidence: "Well-characterised roles in reproductive physiology.",
    safetySummary: "Affects the reproductive hormone axis; only appropriate under clinical/research supervision.",
    knownSideEffects: ["Hormonal effects; context-dependent"],
    commonDiscussion: ["Endocrine research", "Hormone axis"],
    lastReviewed: "2026-06-01",
    reviewedBy: "Editorial team (AI-assisted draft, human-reviewed)",
  },
  {
    slug: "ghrp-2",
    name: "GHRP-2",
    aliases: ["Growth Hormone Releasing Peptide-2"],
    category: "Growth Hormone Secretagogue",
    evidenceScore: "C",
    riskFlag: true,
    commercialRestriction: "restricted",
    regulatoryStatus: "Not an approved medicine for general use. Research chemical status.",
    summary: "A growth-hormone-releasing peptide with limited human evidence and hormonal risks.",
    whatIsIt: "GHRP-2 is a synthetic growth-hormone secretagogue.",
    mechanisms: ["Ghrelin-receptor-mediated growth-hormone release"],
    humanEvidence: "Some pharmacological study history; not an approved therapy.",
    animalEvidence: "Preclinical GH-release effects documented.",
    safetySummary: "Hormonal effects carry real risks; not a validated therapy.",
    knownSideEffects: ["Increased appetite", "Water retention reported"],
    commonDiscussion: ["GH axis", "Appetite"],
    lastReviewed: "2026-06-01",
    reviewedBy: "Editorial team (AI-assisted draft, human-reviewed)",
  },
  {
    slug: "ghrp-6",
    name: "GHRP-6",
    aliases: ["Growth Hormone Releasing Peptide-6"],
    category: "Growth Hormone Secretagogue",
    evidenceScore: "C",
    riskFlag: true,
    commercialRestriction: "restricted",
    regulatoryStatus: "Not an approved medicine for general use. Research chemical status.",
    summary: "A growth-hormone-releasing peptide known for strong appetite effects. Limited human evidence.",
    whatIsIt: "GHRP-6 is a synthetic growth-hormone secretagogue.",
    mechanisms: ["Ghrelin-receptor-mediated growth-hormone release"],
    humanEvidence: "Some pharmacological study history; not an approved therapy.",
    animalEvidence: "Preclinical GH-release and appetite effects documented.",
    safetySummary: "Hormonal effects carry real risks; not a validated therapy.",
    knownSideEffects: ["Strong appetite increase", "Water retention reported"],
    commonDiscussion: ["GH axis", "Appetite"],
    lastReviewed: "2026-06-01",
    reviewedBy: "Editorial team (AI-assisted draft, human-reviewed)",
  },
  {
    slug: "glp-1-class",
    name: "GLP-1 Class (Overview)",
    aliases: ["GLP-1 receptor agonists"],
    category: "Metabolic",
    evidenceScore: "A",
    riskFlag: true,
    commercialRestriction: "restricted",
    regulatoryStatus:
      "Several GLP-1 receptor agonists are approved prescription medicines. Prescription-only; not for unsupervised research-market use.",
    summary:
      "An overview of the GLP-1 receptor agonist class. These are approved prescription medicines — this page is informational only and not a source or promotion.",
    whatIsIt:
      "GLP-1 receptor agonists are a class of approved prescription medicines for diabetes and weight management. Some peptides in this class are subject to strict regulation.",
    mechanisms: ["GLP-1 receptor agonism affecting glucose regulation and appetite"],
    humanEvidence: "Strong clinical evidence and regulatory approval for approved products within the class.",
    animalEvidence: "Extensively characterised.",
    safetySummary:
      "These are prescription medicines that must be used under medical supervision. peptides.cx does not facilitate access to prescription medicines and does not permit affiliate promotion of prescription-only products to consumers.",
    knownSideEffects: ["Nausea", "Gastrointestinal effects", "See approved prescribing information"],
    commonDiscussion: ["Regulatory status", "Approved use only"],
    lastReviewed: "2026-06-01",
    reviewedBy: "Editorial team (AI-assisted draft, human-reviewed)",
  },
]

export function getPeptide(slug: string): Peptide | undefined {
  return peptides.find((p) => p.slug === slug)
}
