export type EvidenceScore = "A" | "B" | "C" | "D"

export type CommercialRestriction =
  | "open" // affiliate promotion allowed where legally permitted
  | "restricted" // no direct affiliate promotion allowed

export interface Peptide {
  slug: string
  name: string
  aliases: string[]
  category: string
  evidenceScore: EvidenceScore
  riskFlag: boolean
  commercialRestriction: CommercialRestriction
  regulatoryStatus: string
  summary: string
  whatIsIt: string
  mechanisms: string[]
  humanEvidence: string
  animalEvidence: string
  safetySummary: string
  knownSideEffects: string[]
  commonDiscussion: string[]
  lastReviewed: string
  reviewedBy: string
}

export const EVIDENCE_SCORE_META: Record<
  EvidenceScore,
  { label: string; description: string; tone: "high" | "mid" | "low" }
> = {
  A: {
    label: "A — Approved / Strong",
    description: "Approved medical use or strong clinical evidence.",
    tone: "high",
  },
  B: {
    label: "B — Human, limited",
    description: "Human evidence exists but is limited.",
    tone: "mid",
  },
  C: {
    label: "C — Early / Preclinical",
    description: "Mostly early human, animal, or mechanistic data.",
    tone: "mid",
  },
  D: {
    label: "D — Anecdotal",
    description: "Anecdotal or insufficient evidence.",
    tone: "low",
  },
}

export const peptides: Peptide[] = [
  {
    slug: "bpc-157",
    name: "BPC-157",
    aliases: ["Body Protection Compound-157", "PL 14736"],
    category: "Recovery / Regeneration",
    evidenceScore: "C",
    riskFlag: true,
    commercialRestriction: "restricted",
    regulatoryStatus:
      "Not an approved medicine in the EU/US. Sold as a research chemical only; not authorised for human use.",
    summary:
      "A synthetic peptide fragment widely discussed for soft-tissue recovery. Human clinical evidence is very limited; most data is animal or mechanistic.",
    whatIsIt:
      "BPC-157 is a synthetic 15-amino-acid sequence derived from a protein found in gastric juice. It is discussed in the community mainly in the context of tendon, ligament, and gut-related recovery.",
    mechanisms: [
      "Proposed promotion of angiogenesis (new blood-vessel formation)",
      "Discussed modulation of growth-factor and nitric-oxide pathways",
      "Proposed effects on fibroblast activity in connective tissue",
    ],
    humanEvidence:
      "Peer-reviewed human clinical trials are essentially absent. Claims about human recovery are extrapolated from animal work and personal reports.",
    animalEvidence:
      "A body of rodent studies reports accelerated healing of tendon, muscle, and gut tissue. These results have not been replicated in controlled human trials.",
    safetySummary:
      "Human safety data is lacking. Purity, sterility, and dosing of research-grade material are unverified. This is not a substitute for professional medical care.",
    knownSideEffects: [
      "Injection-site reactions reported anecdotally",
      "Unknown long-term safety profile",
    ],
    commonDiscussion: ["Tendon and ligament recovery", "Gut discomfort", "Post-injury reports"],
    lastReviewed: "2026-06-01",
    reviewedBy: "Editorial team (AI-assisted draft, human-reviewed)",
  },
  {
    slug: "tb-500",
    name: "TB-500 / Thymosin Beta-4",
    aliases: ["Thymosin Beta-4", "TB4"],
    category: "Recovery / Regeneration",
    evidenceScore: "C",
    riskFlag: true,
    commercialRestriction: "restricted",
    regulatoryStatus:
      "Not an approved medicine for general human use. Research chemical status in most jurisdictions.",
    summary:
      "A peptide related to the naturally occurring protein Thymosin Beta-4, discussed for recovery and regeneration. Human evidence is limited.",
    whatIsIt:
      "TB-500 is a synthetic fragment associated with Thymosin Beta-4, a protein involved in cell migration and actin regulation.",
    mechanisms: [
      "Proposed regulation of actin, supporting cell migration",
      "Discussed roles in angiogenesis and tissue repair",
    ],
    humanEvidence:
      "Limited. Thymosin Beta-4 itself has been studied in some clinical contexts, but the research-market 'TB-500' fragment lacks robust human trials.",
    animalEvidence: "Animal studies suggest roles in wound healing and cardiac tissue repair.",
    safetySummary:
      "Human safety data is limited. Material sold on the research market is not quality-assured for human use.",
    knownSideEffects: ["Fatigue reported anecdotally", "Unknown long-term profile"],
    commonDiscussion: ["Recovery reports", "Comparison with BPC-157"],
    lastReviewed: "2026-06-01",
    reviewedBy: "Editorial team (AI-assisted draft, human-reviewed)",
  },
  {
    slug: "ghk-cu",
    name: "GHK-Cu",
    aliases: ["Copper Peptide", "Copper tripeptide-1"],
    category: "Skin / Cosmetic",
    evidenceScore: "B",
    riskFlag: false,
    commercialRestriction: "open",
    regulatoryStatus:
      "Widely used as a cosmetic ingredient in topical products. Cosmetic use is broadly permitted; injectable use is a separate matter.",
    summary:
      "A copper-binding tripeptide common in cosmetics. There is reasonable evidence for topical skin benefits; systemic/injected use is far less studied.",
    whatIsIt:
      "GHK-Cu is a naturally occurring copper-binding peptide used extensively in topical skincare formulations.",
    mechanisms: [
      "Copper delivery relevant to skin remodelling",
      "Discussed effects on collagen and antioxidant pathways",
    ],
    humanEvidence:
      "Topical cosmetic studies report improvements in skin appearance. Evidence for injected/systemic use is limited.",
    animalEvidence: "Animal and in-vitro work supports wound-healing and skin-remodelling roles.",
    safetySummary:
      "Topical cosmetic use is generally well tolerated. Injected use is not a validated cosmetic route and carries different risks.",
    knownSideEffects: ["Topical irritation in some users"],
    commonDiscussion: ["Skin quality", "Hair", "Topical vs injected"],
    lastReviewed: "2026-06-01",
    reviewedBy: "Editorial team (AI-assisted draft, human-reviewed)",
  },
  {
    slug: "kpv",
    name: "KPV",
    aliases: ["Lysine-Proline-Valine"],
    category: "Inflammation",
    evidenceScore: "C",
    riskFlag: false,
    commercialRestriction: "restricted",
    regulatoryStatus: "Not an approved medicine. Research chemical status.",
    summary:
      "A short tripeptide fragment of alpha-MSH discussed in the context of inflammation. Human evidence is limited.",
    whatIsIt: "KPV is the C-terminal tripeptide of the alpha-MSH hormone, studied for anti-inflammatory properties.",
    mechanisms: ["Discussed anti-inflammatory signalling", "Proposed effects on gut inflammation"],
    humanEvidence: "Very limited human data.",
    animalEvidence: "Preclinical work suggests anti-inflammatory activity in models of colitis.",
    safetySummary: "Human safety data is limited; research-market purity is unverified.",
    knownSideEffects: ["Unknown long-term profile"],
    commonDiscussion: ["Gut inflammation", "Skin"],
    lastReviewed: "2026-06-01",
    reviewedBy: "Editorial team (AI-assisted draft, human-reviewed)",
  },
  {
    slug: "semax",
    name: "Semax",
    aliases: ["ACTH(4-7) analogue"],
    category: "Cognitive",
    evidenceScore: "C",
    riskFlag: false,
    commercialRestriction: "restricted",
    regulatoryStatus:
      "Approved/used as a medicine in some countries (e.g. Russia); not approved in the EU/US.",
    summary:
      "A peptide discussed for cognitive and neuroprotective effects. Approved in some jurisdictions but not others.",
    whatIsIt: "Semax is a synthetic peptide derived from an ACTH fragment, studied for nootropic and neuroprotective effects.",
    mechanisms: ["Discussed modulation of BDNF", "Proposed neuroprotective signalling"],
    humanEvidence: "Some human studies exist in the countries where it is used clinically; broader independent replication is limited.",
    animalEvidence: "Preclinical work reports neuroprotective and cognitive effects.",
    safetySummary: "Where used clinically it is intranasal and prescribed; research-market use is unverified.",
    knownSideEffects: ["Nasal irritation with intranasal use reported"],
    commonDiscussion: ["Focus", "Mood", "Comparison with Selank"],
    lastReviewed: "2026-06-01",
    reviewedBy: "Editorial team (AI-assisted draft, human-reviewed)",
  },
  {
    slug: "selank",
    name: "Selank",
    aliases: ["TP-7 analogue"],
    category: "Cognitive / Mood",
    evidenceScore: "C",
    riskFlag: false,
    commercialRestriction: "restricted",
    regulatoryStatus: "Used as a medicine in some countries; not approved in the EU/US.",
    summary: "An anxiolytic-discussed peptide analogue. Approved in some jurisdictions, limited independent evidence elsewhere.",
    whatIsIt: "Selank is a synthetic analogue of the endogenous peptide tuftsin, studied for anxiolytic effects.",
    mechanisms: ["Discussed effects on GABA and monoamine systems"],
    humanEvidence: "Some regional clinical use; limited independent replication.",
    animalEvidence: "Preclinical anxiolytic effects reported.",
    safetySummary: "Research-market purity is unverified; not a validated treatment outside its regional approvals.",
    knownSideEffects: ["Nasal irritation with intranasal use reported"],
    commonDiscussion: ["Anxiety", "Sleep", "Stacking with Semax"],
    lastReviewed: "2026-06-01",
    reviewedBy: "Editorial team (AI-assisted draft, human-reviewed)",
  },
  {
    slug: "epitalon",
    name: "Epitalon",
    aliases: ["Epithalon", "AEDG"],
    category: "Longevity",
    evidenceScore: "D",
    riskFlag: false,
    commercialRestriction: "restricted",
    regulatoryStatus: "Not an approved medicine. Research chemical status.",
    summary: "A tetrapeptide discussed in longevity circles for telomerase-related claims. Human evidence is weak.",
    whatIsIt: "Epitalon is a synthetic tetrapeptide studied primarily in Russian gerontology research.",
    mechanisms: ["Proposed effects on telomerase activity", "Discussed circadian and pineal effects"],
    humanEvidence: "Sparse and largely from a small number of research groups; independent replication is limited.",
    animalEvidence: "Some rodent longevity data reported by originating groups.",
    safetySummary: "Human safety data is weak. Claims should be treated with caution.",
    knownSideEffects: ["Unknown long-term profile"],
    commonDiscussion: ["Longevity", "Sleep", "Telomeres"],
    lastReviewed: "2026-06-01",
    reviewedBy: "Editorial team (AI-assisted draft, human-reviewed)",
  },
  {
    slug: "mots-c",
    name: "MOTS-c",
    aliases: ["Mitochondrial ORF of the 12S rRNA type-c"],
    category: "Metabolic",
    evidenceScore: "C",
    riskFlag: false,
    commercialRestriction: "restricted",
    regulatoryStatus: "Not an approved medicine. Research chemical status.",
    summary: "A mitochondrial-derived peptide discussed for metabolic effects. Mostly preclinical evidence.",
    whatIsIt: "MOTS-c is a peptide encoded in mitochondrial DNA, studied for roles in metabolism and exercise physiology.",
    mechanisms: ["Discussed AMPK activation", "Proposed metabolic-regulation roles"],
    humanEvidence: "Limited; mostly observational and mechanistic.",
    animalEvidence: "Rodent studies report effects on insulin sensitivity and metabolism.",
    safetySummary: "Human safety data is limited; research-market material is unverified.",
    knownSideEffects: ["Unknown long-term profile"],
    commonDiscussion: ["Metabolism", "Endurance"],
    lastReviewed: "2026-06-01",
    reviewedBy: "Editorial team (AI-assisted draft, human-reviewed)",
  },
  {
    slug: "dsip",
    name: "DSIP",
    aliases: ["Delta Sleep-Inducing Peptide"],
    category: "Sleep",
    evidenceScore: "D",
    riskFlag: false,
    commercialRestriction: "restricted",
    regulatoryStatus: "Not an approved medicine. Research chemical status.",
    summary: "A peptide historically studied for sleep. Human evidence is old and inconsistent.",
    whatIsIt: "DSIP is a neuropeptide first described in relation to sleep regulation.",
    mechanisms: ["Discussed effects on sleep architecture and stress hormones"],
    humanEvidence: "Older human studies exist with mixed and inconsistent results.",
    animalEvidence: "Mixed preclinical findings.",
    safetySummary: "Human safety data is limited and dated.",
    knownSideEffects: ["Unknown long-term profile"],
    commonDiscussion: ["Sleep quality", "Stress"],
    lastReviewed: "2026-06-01",
    reviewedBy: "Editorial team (AI-assisted draft, human-reviewed)",
  },
  {
    slug: "ipamorelin",
    name: "Ipamorelin",
    aliases: ["Growth hormone secretagogue"],
    category: "Growth Hormone Secretagogue",
    evidenceScore: "C",
    riskFlag: true,
    commercialRestriction: "restricted",
    regulatoryStatus: "Not an approved medicine for general use. Research chemical status.",
    summary: "A growth-hormone secretagogue discussed for recovery and body composition. Limited human trial evidence.",
    whatIsIt: "Ipamorelin is a selective growth-hormone secretagogue peptide.",
    mechanisms: ["Stimulation of growth-hormone release via ghrelin-receptor pathways"],
    humanEvidence: "Some early clinical study history; not an approved therapy.",
    animalEvidence: "Preclinical GH-release effects documented.",
    safetySummary: "Hormonal effects carry real risks; not a validated therapy. Professional supervision matters for anything hormonal.",
    knownSideEffects: ["Water retention reported", "Headache reported"],
    commonDiscussion: ["Recovery", "Sleep", "Stacking with CJC-1295"],
    lastReviewed: "2026-06-01",
    reviewedBy: "Editorial team (AI-assisted draft, human-reviewed)",
  },
  {
    slug: "cjc-1295",
    name: "CJC-1295",
    aliases: ["GRF analogue"],
    category: "Growth Hormone Secretagogue",
    evidenceScore: "C",
    riskFlag: true,
    commercialRestriction: "restricted",
    regulatoryStatus: "Not an approved medicine for general use. Research chemical status.",
    summary: "A growth-hormone-releasing factor analogue, often discussed alongside Ipamorelin. Limited human evidence.",
    whatIsIt: "CJC-1295 is a synthetic analogue of growth-hormone-releasing hormone (GHRH).",
    mechanisms: ["Stimulation of endogenous growth-hormone release"],
    humanEvidence: "Limited early clinical history; not an approved therapy.",
    animalEvidence: "Preclinical GH-axis effects documented.",
    safetySummary: "Hormonal effects carry real risks; not a validated therapy.",
    knownSideEffects: ["Injection-site reactions reported", "Water retention reported"],
    commonDiscussion: ["GH axis", "Recovery"],
    lastReviewed: "2026-06-01",
    reviewedBy: "Editorial team (AI-assisted draft, human-reviewed)",
  },
  {
    slug: "aod-9604",
    name: "AOD-9604",
    aliases: ["hGH fragment 176-191"],
    category: "Metabolic",
    evidenceScore: "C",
    riskFlag: false,
    commercialRestriction: "restricted",
    regulatoryStatus: "Not an approved weight-loss medicine; clinical development did not lead to approval.",
    summary: "A growth-hormone fragment once investigated for fat loss. Clinical trials did not lead to approval.",
    whatIsIt: "AOD-9604 is a fragment of human growth hormone investigated for metabolic effects.",
    mechanisms: ["Discussed effects on lipolysis without the full GH profile"],
    humanEvidence: "Clinical trials for obesity did not demonstrate sufficient efficacy for approval.",
    animalEvidence: "Some preclinical lipolytic effects reported.",
    safetySummary: "Not an approved therapy; efficacy for fat loss is not established.",
    knownSideEffects: ["Unknown long-term profile"],
    commonDiscussion: ["Fat loss", "Metabolism"],
    lastReviewed: "2026-06-01",
    reviewedBy: "Editorial team (AI-assisted draft, human-reviewed)",
  },
  {
    slug: "melanotan-1",
    name: "Melanotan I",
    aliases: ["Afamelanotide (related)"],
    category: "Pigmentation",
    evidenceScore: "B",
    riskFlag: true,
    commercialRestriction: "restricted",
    regulatoryStatus:
      "A related compound (afamelanotide) is an approved medicine for a rare condition; research-market Melanotan I is not.",
    summary: "A melanocortin agonist related to an approved medicine. Research-market use is unregulated and carries risks.",
    whatIsIt: "Melanotan I is a synthetic analogue of alpha-MSH affecting pigmentation.",
    mechanisms: ["Melanocortin-1 receptor agonism affecting melanin production"],
    humanEvidence: "The related approved drug has clinical evidence for a specific rare condition; general research-market use does not.",
    animalEvidence: "Melanocortin effects well characterised preclinically.",
    safetySummary: "Unregulated research-market use carries risks including effects on existing moles; dermatological monitoring matters.",
    knownSideEffects: ["Nausea reported", "Darkening of moles/freckles reported"],
    commonDiscussion: ["Pigmentation", "Photoprotection context"],
    lastReviewed: "2026-06-01",
    reviewedBy: "Editorial team (AI-assisted draft, human-reviewed)",
  },
  {
    slug: "melanotan-2",
    name: "Melanotan II",
    aliases: ["MT-2"],
    category: "Pigmentation",
    evidenceScore: "C",
    riskFlag: true,
    commercialRestriction: "restricted",
    regulatoryStatus: "Not an approved medicine. Sale for human use is restricted in many countries.",
    summary: "A non-selective melanocortin agonist widely flagged by regulators for safety concerns.",
    whatIsIt: "Melanotan II is a synthetic melanocortin agonist affecting pigmentation and other pathways.",
    mechanisms: ["Non-selective melanocortin-receptor agonism"],
    humanEvidence: "No approval; multiple regulator safety warnings exist.",
    animalEvidence: "Melanocortin effects characterised preclinically.",
    safetySummary: "Regulators have issued safety warnings. Effects on moles, blood pressure, and other systems are of concern.",
    knownSideEffects: ["Nausea", "Flushing", "Darkening of moles reported"],
    commonDiscussion: ["Pigmentation", "Safety warnings"],
    lastReviewed: "2026-06-01",
    reviewedBy: "Editorial team (AI-assisted draft, human-reviewed)",
  },
  {
    slug: "thymosin-alpha-1",
    name: "Thymosin Alpha-1",
    aliases: ["Ta1", "Thymalfasin"],
    category: "Immune",
    evidenceScore: "B",
    riskFlag: false,
    commercialRestriction: "restricted",
    regulatoryStatus:
      "Approved as a medicine (thymalfasin) in some countries for specific indications; not universally approved.",
    summary: "An immune-modulating peptide approved in some countries for specific conditions.",
    whatIsIt: "Thymosin Alpha-1 is a peptide involved in immune regulation, marketed as thymalfasin in some regions.",
    mechanisms: ["Immune modulation, including effects on T-cell function"],
    humanEvidence: "Clinical evidence exists for specific approved indications in the countries where it is registered.",
    animalEvidence: "Immune-modulating effects documented preclinically.",
    safetySummary: "Where approved it is prescribed and monitored; research-market use is unverified.",
    knownSideEffects: ["Injection-site reactions reported"],
    commonDiscussion: ["Immune support context", "Approved use vs research use"],
    lastReviewed: "2026-06-01",
    reviewedBy: "Editorial team (AI-assisted draft, human-reviewed)",
  },
  {
    slug: "ll-37",
    name: "LL-37",
    aliases: ["Cathelicidin fragment"],
    category: "Antimicrobial / Immune",
    evidenceScore: "C",
    riskFlag: false,
    commercialRestriction: "restricted",
    regulatoryStatus: "Not an approved medicine. Research chemical status.",
    summary: "An antimicrobial peptide studied for immune and antimicrobial roles. Mostly preclinical.",
    whatIsIt: "LL-37 is a human cathelicidin-derived antimicrobial peptide.",
    mechanisms: ["Antimicrobial activity", "Immune-modulating roles"],
    humanEvidence: "Limited; largely mechanistic and preclinical.",
    animalEvidence: "Antimicrobial and immune effects reported.",
    safetySummary: "Human safety data is limited; research-market material is unverified.",
    knownSideEffects: ["Unknown long-term profile"],
    commonDiscussion: ["Immune", "Skin"],
    lastReviewed: "2026-06-01",
    reviewedBy: "Editorial team (AI-assisted draft, human-reviewed)",
  },
  {
    slug: "kisspeptin-10",
    name: "Kisspeptin-10",
    aliases: ["KP-10"],
    category: "Endocrine",
    evidenceScore: "B",
    riskFlag: true,
    commercialRestriction: "restricted",
    regulatoryStatus: "Investigational; used in some clinical research settings. Not a general-use medicine.",
    summary: "A reproductive-hormone-axis peptide studied in clinical research. Not a consumer product.",
    whatIsIt: "Kisspeptin-10 is a peptide central to the regulation of reproductive hormones.",
    mechanisms: ["Stimulation of GnRH and downstream reproductive hormones"],
    humanEvidence: "Studied in controlled clinical research on reproductive endocrinology.",
    animalEvidence: "Well-characterised roles in reproductive physiology.",
    safetySummary: "Affects the reproductive hormone axis; only appropriate under clinical/research supervision.",
    knownSideEffects: ["Hormonal effects; context-dependent"],
    commonDiscussion: ["Endocrine research", "Hormone axis"],
    lastReviewed: "2026-06-01",
    reviewedBy: "Editorial team (AI-assisted draft, human-reviewed)",
  },
  {
    slug: "ghrp-2",
    name: "GHRP-2",
    aliases: ["Growth Hormone Releasing Peptide-2"],
    category: "Growth Hormone Secretagogue",
    evidenceScore: "C",
    riskFlag: true,
    commercialRestriction: "restricted",
    regulatoryStatus: "Not an approved medicine for general use. Research chemical status.",
    summary: "A growth-hormone-releasing peptide with limited human evidence and hormonal risks.",
    whatIsIt: "GHRP-2 is a synthetic growth-hormone secretagogue.",
    mechanisms: ["Ghrelin-receptor-mediated growth-hormone release"],
    humanEvidence: "Some pharmacological study history; not an approved therapy.",
    animalEvidence: "Preclinical GH-release effects documented.",
    safetySummary: "Hormonal effects carry real risks; not a validated therapy.",
    knownSideEffects: ["Increased appetite", "Water retention reported"],
    commonDiscussion: ["GH axis", "Appetite"],
    lastReviewed: "2026-06-01",
    reviewedBy: "Editorial team (AI-assisted draft, human-reviewed)",
  },
  {
    slug: "ghrp-6",
    name: "GHRP-6",
    aliases: ["Growth Hormone Releasing Peptide-6"],
    category: "Growth Hormone Secretagogue",
    evidenceScore: "C",
    riskFlag: true,
    commercialRestriction: "restricted",
    regulatoryStatus: "Not an approved medicine for general use. Research chemical status.",
    summary: "A growth-hormone-releasing peptide known for strong appetite effects. Limited human evidence.",
    whatIsIt: "GHRP-6 is a synthetic growth-hormone secretagogue.",
    mechanisms: ["Ghrelin-receptor-mediated growth-hormone release"],
    humanEvidence: "Some pharmacological study history; not an approved therapy.",
    animalEvidence: "Preclinical GH-release and appetite effects documented.",
    safetySummary: "Hormonal effects carry real risks; not a validated therapy.",
    knownSideEffects: ["Strong appetite increase", "Water retention reported"],
    commonDiscussion: ["GH axis", "Appetite"],
    lastReviewed: "2026-06-01",
    reviewedBy: "Editorial team (AI-assisted draft, human-reviewed)",
  },
  {
    slug: "glp-1-class",
    name: "GLP-1 Class (Overview)",
    aliases: ["GLP-1 receptor agonists"],
    category: "Metabolic",
    evidenceScore: "A",
    riskFlag: true,
    commercialRestriction: "restricted",
    regulatoryStatus:
      "Several GLP-1 receptor agonists are approved prescription medicines. Prescription-only; not for unsupervised research-market use.",
    summary:
      "An overview of the GLP-1 receptor agonist class. These are approved prescription medicines — this page is informational only and not a source or promotion.",
    whatIsIt:
      "GLP-1 receptor agonists are a class of approved prescription medicines for diabetes and weight management. Some peptides in this class are subject to strict regulation.",
    mechanisms: ["GLP-1 receptor agonism affecting glucose regulation and appetite"],
    humanEvidence: "Strong clinical evidence and regulatory approval for approved products within the class.",
    animalEvidence: "Extensively characterised.",
    safetySummary:
      "These are prescription medicines that must be used under medical supervision. peptides.cx does not facilitate access to prescription medicines and does not permit affiliate promotion of prescription-only products to consumers.",
    knownSideEffects: ["Nausea", "Gastrointestinal effects", "See approved prescribing information"],
    commonDiscussion: ["Regulatory status", "Approved use only"],
    lastReviewed: "2026-06-01",
    reviewedBy: "Editorial team (AI-assisted draft, human-reviewed)",
  },
  {
    slug: "tesamorelin",
    name: "Tesamorelin",
    aliases: ["Egrifta", "TH9507"],
    category: "Growth Hormone Secretagogue",
    evidenceScore: "B",
    riskFlag: true,
    commercialRestriction: "restricted",
    regulatoryStatus:
      "Approved as a prescription medicine (Egrifta) for HIV-associated lipodystrophy in some jurisdictions; prescription-only.",
    summary:
      "A GHRH analogue approved as a prescription medicine for a specific condition. Research-market use is unapproved and unsupervised.",
    whatIsIt: "Tesamorelin is a stabilised analogue of growth-hormone-releasing hormone.",
    mechanisms: ["Stimulates endogenous growth-hormone release via the GHRH pathway"],
    humanEvidence: "Clinical evidence supports its approved indication; other uses are not established.",
    animalEvidence: "GH-axis effects characterised preclinically.",
    safetySummary:
      "A prescription medicine with real hormonal effects; must be used under medical supervision. Not for unsupervised use.",
    knownSideEffects: ["Injection-site reactions", "Joint pain", "Fluid retention reported"],
    commonDiscussion: ["GH axis", "Approved vs research use"],
    lastReviewed: "2026-06-01",
    reviewedBy: "Editorial team (AI-assisted draft, human-reviewed)",
  },
  {
    slug: "sermorelin",
    name: "Sermorelin",
    aliases: ["GRF 1-29"],
    category: "Growth Hormone Secretagogue",
    evidenceScore: "C",
    riskFlag: true,
    commercialRestriction: "restricted",
    regulatoryStatus:
      "Previously marketed as a medicine for diagnostic/therapeutic use; availability and status vary by country.",
    summary: "A GHRH fragment historically used clinically, now common in research and compounding contexts.",
    whatIsIt: "Sermorelin is a peptide corresponding to the first 29 amino acids of GHRH.",
    mechanisms: ["Stimulates pituitary growth-hormone release"],
    humanEvidence: "Some historical clinical use; modern research-market use is not a validated therapy.",
    animalEvidence: "GH-release effects documented.",
    safetySummary: "Hormonal effects carry real risks; supervision matters for anything affecting the GH axis.",
    knownSideEffects: ["Injection-site reactions", "Flushing reported"],
    commonDiscussion: ["GH axis", "Comparison with CJC-1295"],
    lastReviewed: "2026-06-01",
    reviewedBy: "Editorial team (AI-assisted draft, human-reviewed)",
  },
  {
    slug: "hexarelin",
    name: "Hexarelin",
    aliases: ["Examorelin"],
    category: "Growth Hormone Secretagogue",
    evidenceScore: "C",
    riskFlag: true,
    commercialRestriction: "restricted",
    regulatoryStatus: "Not an approved medicine for general use. Research chemical status.",
    summary: "A potent growth-hormone-releasing peptide with limited human evidence and hormonal risks.",
    whatIsIt: "Hexarelin is a synthetic hexapeptide growth-hormone secretagogue.",
    mechanisms: ["Ghrelin-receptor-mediated GH release", "Discussed cardiac effects"],
    humanEvidence: "Limited pharmacological study history; not an approved therapy.",
    animalEvidence: "GH-release and cardiovascular effects reported preclinically.",
    safetySummary: "Hormonal effects and potential desensitisation; not a validated therapy.",
    knownSideEffects: ["Water retention", "Prolactin/cortisol effects reported"],
    commonDiscussion: ["GH axis", "Tolerance"],
    lastReviewed: "2026-06-01",
    reviewedBy: "Editorial team (AI-assisted draft, human-reviewed)",
  },
  {
    slug: "mgf",
    name: "MGF / PEG-MGF",
    aliases: ["Mechano Growth Factor", "IGF-1Ec"],
    category: "Growth Factor",
    evidenceScore: "D",
    riskFlag: true,
    commercialRestriction: "restricted",
    regulatoryStatus: "Not an approved medicine. Research chemical status; prohibited in sport.",
    summary: "A splice variant of IGF-1 discussed for muscle repair. Human evidence is minimal.",
    whatIsIt: "MGF is a mechano-growth-factor splice variant of IGF-1; PEG-MGF is a pegylated form.",
    mechanisms: ["Discussed roles in muscle satellite-cell activation"],
    humanEvidence: "Minimal; largely mechanistic and anecdotal.",
    animalEvidence: "Some muscle-repair signalling reported.",
    safetySummary: "Growth-factor signalling carries theoretical risks; unverified research-market material.",
    knownSideEffects: ["Unknown long-term profile"],
    commonDiscussion: ["Muscle repair", "IGF pathway"],
    lastReviewed: "2026-06-01",
    reviewedBy: "Editorial team (AI-assisted draft, human-reviewed)",
  },
  {
    slug: "igf-1-lr3",
    name: "IGF-1 LR3",
    aliases: ["Long R3 IGF-1"],
    category: "Growth Factor",
    evidenceScore: "C",
    riskFlag: true,
    commercialRestriction: "restricted",
    regulatoryStatus: "Not an approved medicine for general use; prohibited in sport. Research chemical status.",
    summary: "A long-acting IGF-1 analogue with significant hormonal/growth-factor risks and little human safety data.",
    whatIsIt: "IGF-1 LR3 is a modified insulin-like growth factor 1 with extended half-life.",
    mechanisms: ["IGF-1 receptor agonism affecting growth and metabolism"],
    humanEvidence: "No approval for the research-market form; safety data is lacking.",
    animalEvidence: "Growth and metabolic effects documented.",
    safetySummary:
      "Potent growth-factor with risks including hypoglycaemia and theoretical proliferative concerns. Not a validated therapy.",
    knownSideEffects: ["Hypoglycaemia risk", "Unknown long-term profile"],
    commonDiscussion: ["IGF pathway", "Risk profile"],
    lastReviewed: "2026-06-01",
    reviewedBy: "Editorial team (AI-assisted draft, human-reviewed)",
  },
  {
    slug: "pt-141",
    name: "PT-141 (Bremelanotide)",
    aliases: ["Bremelanotide", "Vyleesi"],
    category: "Sexual Health",
    evidenceScore: "B",
    riskFlag: true,
    commercialRestriction: "restricted",
    regulatoryStatus:
      "Approved as a prescription medicine (Vyleesi) for a specific indication in some jurisdictions; prescription-only.",
    summary: "A melanocortin agonist approved as a prescription medicine. Research-market use is unregulated.",
    whatIsIt: "PT-141 is a melanocortin-receptor agonist related to the pigmentation peptides.",
    mechanisms: ["Central melanocortin-receptor agonism"],
    humanEvidence: "Clinical evidence supports its approved indication.",
    animalEvidence: "Melanocortin effects characterised.",
    safetySummary: "Can affect blood pressure and cause nausea; prescription medicine that needs supervision.",
    knownSideEffects: ["Nausea", "Flushing", "Transient blood-pressure changes"],
    commonDiscussion: ["Approved use", "Melanocortin system"],
    lastReviewed: "2026-06-01",
    reviewedBy: "Editorial team (AI-assisted draft, human-reviewed)",
  },
  {
    slug: "follistatin",
    name: "Follistatin",
    aliases: ["FST", "FST-344"],
    category: "Muscle / Myostatin",
    evidenceScore: "D",
    riskFlag: true,
    commercialRestriction: "restricted",
    regulatoryStatus: "Not an approved medicine. Research/experimental status.",
    summary: "A myostatin-pathway protein discussed for muscle growth. Human evidence is essentially absent for research-market use.",
    whatIsIt: "Follistatin binds and inhibits myostatin and related factors.",
    mechanisms: ["Myostatin inhibition affecting muscle growth"],
    humanEvidence: "Largely experimental (gene-therapy research); research-market peptide use is unvalidated.",
    animalEvidence: "Muscle-growth effects in models.",
    safetySummary: "Manipulating the myostatin pathway has unknown long-term human risks; unverified material.",
    knownSideEffects: ["Unknown long-term profile"],
    commonDiscussion: ["Myostatin", "Muscle growth"],
    lastReviewed: "2026-06-01",
    reviewedBy: "Editorial team (AI-assisted draft, human-reviewed)",
  },
  {
    slug: "ss-31",
    name: "SS-31 (Elamipretide)",
    aliases: ["Elamipretide", "MTP-131"],
    category: "Mitochondrial",
    evidenceScore: "B",
    riskFlag: false,
    commercialRestriction: "restricted",
    regulatoryStatus: "Investigational; studied in clinical trials. Not an approved general-use medicine.",
    summary: "A mitochondria-targeting peptide studied in clinical trials for mitochondrial disease.",
    whatIsIt: "SS-31 is a cell-permeable peptide that targets cardiolipin in mitochondrial membranes.",
    mechanisms: ["Stabilises cardiolipin, supporting mitochondrial function"],
    humanEvidence: "Studied in controlled clinical trials with mixed results; not approved.",
    animalEvidence: "Protective mitochondrial effects reported.",
    safetySummary: "Investigational; research-market material is not the studied clinical product.",
    knownSideEffects: ["Injection-site reactions reported in trials"],
    commonDiscussion: ["Mitochondria", "Energy"],
    lastReviewed: "2026-06-01",
    reviewedBy: "Editorial team (AI-assisted draft, human-reviewed)",
  },
  {
    slug: "humanin",
    name: "Humanin",
    aliases: ["HN"],
    category: "Mitochondrial",
    evidenceScore: "C",
    riskFlag: false,
    commercialRestriction: "restricted",
    regulatoryStatus: "Not an approved medicine. Research status.",
    summary: "A mitochondrial-derived peptide studied for cytoprotective and metabolic roles. Mostly preclinical.",
    whatIsIt: "Humanin is a peptide encoded in mitochondrial DNA with proposed cytoprotective effects.",
    mechanisms: ["Discussed cytoprotective and metabolic signalling"],
    humanEvidence: "Limited; largely observational and mechanistic.",
    animalEvidence: "Cytoprotective effects reported.",
    safetySummary: "Human safety data is limited; unverified research-market material.",
    knownSideEffects: ["Unknown long-term profile"],
    commonDiscussion: ["Longevity", "Mitochondria"],
    lastReviewed: "2026-06-01",
    reviewedBy: "Editorial team (AI-assisted draft, human-reviewed)",
  },
  {
    slug: "gonadorelin",
    name: "Gonadorelin",
    aliases: ["GnRH"],
    category: "Endocrine",
    evidenceScore: "B",
    riskFlag: true,
    commercialRestriction: "restricted",
    regulatoryStatus: "Approved as a medicine for specific endocrine indications in some jurisdictions; prescription-only.",
    summary: "A gonadotropin-releasing hormone used clinically in reproductive endocrinology.",
    whatIsIt: "Gonadorelin is synthetic GnRH, central to reproductive hormone regulation.",
    mechanisms: ["Stimulates pituitary LH/FSH release"],
    humanEvidence: "Clinical evidence for approved endocrine uses.",
    animalEvidence: "Well characterised.",
    safetySummary: "Affects the reproductive hormone axis; appropriate only under medical supervision.",
    knownSideEffects: ["Hormonal effects; context-dependent"],
    commonDiscussion: ["Endocrine", "Hormone axis"],
    lastReviewed: "2026-06-01",
    reviewedBy: "Editorial team (AI-assisted draft, human-reviewed)",
  },
  {
    slug: "cerebrolysin",
    name: "Cerebrolysin",
    aliases: ["FPF-1070"],
    category: "Cognitive / Neuro",
    evidenceScore: "C",
    riskFlag: false,
    commercialRestriction: "restricted",
    regulatoryStatus: "Used as a medicine in some countries; not approved in the US. Prescription where marketed.",
    summary: "A porcine-brain-derived peptide preparation used clinically in some countries for neurological conditions.",
    whatIsIt: "Cerebrolysin is a mixture of low-molecular-weight peptides and amino acids of neuronal origin.",
    mechanisms: ["Discussed neurotrophic and neuroprotective effects"],
    humanEvidence: "Regional clinical use; independent evidence is mixed.",
    animalEvidence: "Neurotrophic effects reported.",
    safetySummary: "Where used it is prescribed and monitored; research-market material is unverified.",
    knownSideEffects: ["Injection-site reactions reported"],
    commonDiscussion: ["Cognition", "Neuroprotection"],
    lastReviewed: "2026-06-01",
    reviewedBy: "Editorial team (AI-assisted draft, human-reviewed)",
  },
  {
    slug: "n-acetyl-semax",
    name: "N-Acetyl Semax Amidate",
    aliases: ["NA-Semax", "NASA"],
    category: "Cognitive",
    evidenceScore: "C",
    riskFlag: false,
    commercialRestriction: "restricted",
    regulatoryStatus: "Not approved in the EU/US; related to a medicine used in some countries.",
    summary: "A more stable amidated variant of Semax discussed for cognition. Limited independent evidence.",
    whatIsIt: "An acetylated, amidated analogue of Semax intended for greater stability.",
    mechanisms: ["Discussed BDNF modulation", "Proposed neuroprotective signalling"],
    humanEvidence: "Limited; extrapolated largely from Semax research.",
    animalEvidence: "Preclinical cognitive effects reported for the Semax family.",
    safetySummary: "Research-market purity is unverified; not a validated therapy.",
    knownSideEffects: ["Nasal irritation with intranasal use reported"],
    commonDiscussion: ["Focus", "Semax family"],
    lastReviewed: "2026-06-01",
    reviewedBy: "Editorial team (AI-assisted draft, human-reviewed)",
  },
  {
    slug: "dihexa",
    name: "Dihexa",
    aliases: ["N-hexanoic-Tyr-Ile-(6) aminohexanoic amide"],
    category: "Cognitive",
    evidenceScore: "D",
    riskFlag: false,
    commercialRestriction: "restricted",
    regulatoryStatus: "Not an approved medicine. Research chemical status.",
    summary: "An experimental peptide discussed for potent effects on synaptic connections. Human data is essentially absent.",
    whatIsIt: "Dihexa is an angiotensin-IV-derived compound studied for synaptogenesis.",
    mechanisms: ["Discussed HGF/c-Met pathway effects on synapse formation"],
    humanEvidence: "Essentially none.",
    animalEvidence: "Preclinical cognitive effects reported.",
    safetySummary: "No human safety data; proliferative pathway involvement warrants caution.",
    knownSideEffects: ["Unknown profile"],
    commonDiscussion: ["Cognition", "Synaptogenesis"],
    lastReviewed: "2026-06-01",
    reviewedBy: "Editorial team (AI-assisted draft, human-reviewed)",
  },
  {
    slug: "foxo4-dri",
    name: "FOXO4-DRI",
    aliases: ["FOXO4 D-Retro-Inverso"],
    category: "Longevity / Senolytic",
    evidenceScore: "D",
    riskFlag: true,
    commercialRestriction: "restricted",
    regulatoryStatus: "Not an approved medicine. Experimental research compound.",
    summary: "An experimental senolytic peptide discussed in longevity circles. Human evidence is absent.",
    whatIsIt: "FOXO4-DRI is a designed peptide intended to disrupt a FOXO4–p53 interaction in senescent cells.",
    mechanisms: ["Proposed targeting of senescent cells"],
    humanEvidence: "None; preclinical only.",
    animalEvidence: "Some senolytic effects reported in mouse studies.",
    safetySummary: "Highly experimental with unknown human safety; unverified material.",
    knownSideEffects: ["Unknown profile"],
    commonDiscussion: ["Senolytics", "Longevity"],
    lastReviewed: "2026-06-01",
    reviewedBy: "Editorial team (AI-assisted draft, human-reviewed)",
  },
  {
    slug: "adipotide",
    name: "Adipotide",
    aliases: ["FTPP", "Prohibitin-TP01"],
    category: "Metabolic",
    evidenceScore: "D",
    riskFlag: true,
    commercialRestriction: "restricted",
    regulatoryStatus: "Not an approved medicine. Experimental; significant safety concerns.",
    summary: "An experimental fat-loss peptide with serious safety concerns (renal toxicity in studies). Not for human use.",
    whatIsIt: "Adipotide is a peptidomimetic targeting the blood supply of fat tissue.",
    mechanisms: ["Targets vasculature of white adipose tissue"],
    humanEvidence: "None established; primate studies showed renal toxicity.",
    animalEvidence: "Weight loss with nephrotoxicity reported.",
    safetySummary: "Documented kidney toxicity in primate studies. Considered unsafe for human use.",
    knownSideEffects: ["Renal toxicity (in studies)", "Dehydration"],
    commonDiscussion: ["Fat loss", "Safety concerns"],
    lastReviewed: "2026-06-01",
    reviewedBy: "Editorial team (AI-assisted draft, human-reviewed)",
  },
  {
    slug: "thymalin",
    name: "Thymalin",
    aliases: ["Thymus peptide extract"],
    category: "Immune",
    evidenceScore: "C",
    riskFlag: false,
    commercialRestriction: "restricted",
    regulatoryStatus: "Used as a medicine in some countries; not approved in the EU/US.",
    summary: "A thymus-derived peptide preparation discussed for immune modulation. Independent evidence is limited.",
    whatIsIt: "Thymalin is a peptide complex derived from the thymus.",
    mechanisms: ["Discussed immune-modulating effects"],
    humanEvidence: "Regional clinical use; limited independent replication.",
    animalEvidence: "Immune effects reported.",
    safetySummary: "Research-market material is unverified; not a validated therapy where unapproved.",
    knownSideEffects: ["Injection-site reactions reported"],
    commonDiscussion: ["Immune support", "Bioregulators"],
    lastReviewed: "2026-06-01",
    reviewedBy: "Editorial team (AI-assisted draft, human-reviewed)",
  },
  {
    slug: "pinealon",
    name: "Pinealon",
    aliases: ["EDR peptide"],
    category: "Longevity / Bioregulator",
    evidenceScore: "D",
    riskFlag: false,
    commercialRestriction: "restricted",
    regulatoryStatus: "Not an approved medicine. Research status.",
    summary: "A short 'bioregulator' peptide discussed for neuro/longevity effects. Evidence is weak and largely from one research tradition.",
    whatIsIt: "Pinealon is a synthetic tripeptide (Glu-Asp-Arg) from the Russian bioregulator research programme.",
    mechanisms: ["Proposed peptide-bioregulator effects on gene expression"],
    humanEvidence: "Weak; limited independent replication.",
    animalEvidence: "Some neuroprotective claims from originating groups.",
    safetySummary: "Human safety data is weak; treat claims with caution.",
    knownSideEffects: ["Unknown long-term profile"],
    commonDiscussion: ["Bioregulators", "Longevity"],
    lastReviewed: "2026-06-01",
    reviewedBy: "Editorial team (AI-assisted draft, human-reviewed)",
  },
  {
    slug: "argireline",
    name: "Argireline",
    aliases: ["Acetyl Hexapeptide-8", "Acetyl Hexapeptide-3"],
    category: "Skin / Cosmetic",
    evidenceScore: "B",
    riskFlag: false,
    commercialRestriction: "open",
    regulatoryStatus: "Widely used as a topical cosmetic ingredient. Cosmetic use is broadly permitted.",
    summary: "A popular topical cosmetic peptide marketed for the appearance of expression lines. Topical, not injected.",
    whatIsIt: "Argireline is a synthetic peptide used in anti-ageing cosmetic formulations.",
    mechanisms: ["Discussed topical effects on neurotransmitter release at the skin surface"],
    humanEvidence: "Cosmetic studies report modest improvements in the appearance of fine lines.",
    animalEvidence: "Not the primary evidence base; mechanistic/in-vitro data exists.",
    safetySummary: "Generally well tolerated topically. This is a cosmetic ingredient, not an injectable.",
    knownSideEffects: ["Mild topical irritation in some users"],
    commonDiscussion: ["Fine lines", "Topical cosmetics"],
    lastReviewed: "2026-06-01",
    reviewedBy: "Editorial team (AI-assisted draft, human-reviewed)",
  },
  {
    slug: "matrixyl",
    name: "Matrixyl",
    aliases: ["Palmitoyl Pentapeptide-4", "Pal-KTTKS"],
    category: "Skin / Cosmetic",
    evidenceScore: "B",
    riskFlag: false,
    commercialRestriction: "open",
    regulatoryStatus: "Widely used as a topical cosmetic ingredient. Cosmetic use is broadly permitted.",
    summary: "A well-known topical cosmetic peptide marketed for skin firmness and fine lines.",
    whatIsIt: "Matrixyl is a palmitoylated peptide used in topical skincare to support collagen-related pathways.",
    mechanisms: ["Discussed stimulation of extracellular-matrix components in skin"],
    humanEvidence: "Cosmetic studies report improvements in skin appearance.",
    animalEvidence: "Mechanistic/in-vitro support.",
    safetySummary: "Generally well tolerated topically; a cosmetic ingredient, not an injectable.",
    knownSideEffects: ["Rare topical irritation"],
    commonDiscussion: ["Collagen", "Anti-ageing skincare"],
    lastReviewed: "2026-06-01",
    reviewedBy: "Editorial team (AI-assisted draft, human-reviewed)",
  },
  {
    slug: "snap-8",
    name: "SNAP-8",
    aliases: ["Acetyl Octapeptide-3"],
    category: "Skin / Cosmetic",
    evidenceScore: "C",
    riskFlag: false,
    commercialRestriction: "open",
    regulatoryStatus: "Used as a topical cosmetic ingredient. Cosmetic use is broadly permitted.",
    summary: "A topical cosmetic peptide, an extension of the Argireline concept, marketed for expression lines.",
    whatIsIt: "SNAP-8 is an octapeptide used in anti-ageing cosmetics.",
    mechanisms: ["Discussed topical effects on expression-line appearance"],
    humanEvidence: "Limited cosmetic data.",
    animalEvidence: "Mechanistic/in-vitro data.",
    safetySummary: "Topical cosmetic ingredient; generally well tolerated.",
    knownSideEffects: ["Mild topical irritation in some users"],
    commonDiscussion: ["Fine lines", "Cosmetics"],
    lastReviewed: "2026-06-01",
    reviewedBy: "Editorial team (AI-assisted draft, human-reviewed)",
  },
  {
    slug: "vip",
    name: "VIP",
    aliases: ["Vasoactive Intestinal Peptide"],
    category: "Immune / Neuro",
    evidenceScore: "C",
    riskFlag: true,
    commercialRestriction: "restricted",
    regulatoryStatus: "Not an approved general-use medicine; used in specific medical/diagnostic contexts.",
    summary: "A signalling peptide discussed in niche protocols. Affects vasculature and immune signalling; not a casual compound.",
    whatIsIt: "VIP is an endogenous peptide with roles in vasodilation and immune/neural signalling.",
    mechanisms: ["Vasodilation", "Immune and neuroendocrine signalling"],
    humanEvidence: "Limited outside specific medical contexts.",
    animalEvidence: "Well characterised physiologically.",
    safetySummary: "Can affect blood pressure; appropriate only under medical supervision.",
    knownSideEffects: ["Flushing", "Blood-pressure effects"],
    commonDiscussion: ["Immune", "Niche protocols"],
    lastReviewed: "2026-06-01",
    reviewedBy: "Editorial team (AI-assisted draft, human-reviewed)",
  },
]

export function getPeptide(slug: string): Peptide | undefined {
  return peptides.find((p) => p.slug === slug)
}
